document.write('<link href="https://fonts.googleapis.com/css?family=Titillium+Web|&subset=latin,latin-ext" rel="stylesheet" type="text/css">');
document.write('<style>');
document.write('.navbar .navbar-expand-lg{');
document.write('padding:0;');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7{');
document.write('background-color:rgba(84,27,19,1);');
document.write('padding:0;');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .navbar-nav .nav-link{');
document.write('color:rgba(248,255,30,1);');
document.write('background-color:transparent;');
document.write('font-family:"Titillium Web";');
document.write('font-size:15px;');
document.write('padding-left:10px;');
document.write('}');
document.write('.nav-link{');
document.write('padding:1rem;');
document.write('background-color:transparent;');
document.write('}');
document.write('.navbar-toggler{');
document.write('padding:1rem;');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .navbar-nav .nav-link:focus,.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .navbar-nav .nav-link:hover{');
document.write('color:rgba(99,11,18,1) !important;');
document.write('background-color:rgba(255,255,255,1);');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .navbar-brand{');
document.write('color:rgba(248,255,30,1);');
document.write('background-color:transparent;');
document.write('font-family:"Titillium Web";');
document.write('font-size:17px;');
document.write('padding-left:0.5rem;');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .nav-item{');
document.write('background-color:transparent;');
document.write('}');
document.write('.custom_navbar_icon{');
document.write('color:rgba(248,255,30,1);');
document.write('background-color:transparent;');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .navbar-brand:focus,.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .navbar-brand:hover{');
document.write('color:rgba(248,255,30,1);');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .dropdown-menu{');
document.write('background-color:rgba(84,27,19,1);');
document.write('padding:0;');
document.write('margin:0;');
document.write('}');
document.write('.dropdown-toggle:after{');
document.write('color:rgba(248,255,30,1);');
document.write('}');
document.write('.dropdown, .dropup{');
document.write('color:rgba(248,255,30,1);');
document.write('}');
document.write('.navbar_Cb1d337b31bd34d5a88bf0f66cd20f4d7 .navbar-toggler-icon{');
document.write('background-image:url("data:image/svg+xml;charset=utf8,%3Csvg viewBox=\'0 0 32 32\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath stroke=\'rgba(248,255,30,1)\' stroke-width=\'3\' stroke-linecap=\'round\' stroke-miterlimit=\'10\' d=\'M4 8h24M4 16h24M4 24h24\'/%3E%3C/svg%3E");');
document.write('}');
document.write('.Cd2e9a5c7cdd04833b0766feae36de821{');
document.write('padding-left:10px;');
document.write('padding-right:10px;');
document.write('padding-top:0px;');
document.write('padding-bottom:0px;');
document.write('}');
document.write('.C3afd58f1d4cd4242a3b2fd42b16041c5{');
document.write('padding-left:2.5%;');
document.write('padding-right:2.5%;');
document.write('padding-top:0px;');
document.write('padding-bottom:0px;');
document.write('background: url("hazel_header/spark pictures_n.jpg") no-repeat center top;');
document.write('-webkit-background-size:cover;');
document.write('-moz-background-size:cover;');
document.write('-o-background-size:cover;');
document.write('background-size:cover;');
document.write('min-height:94px;');
document.write('margin-left:0%;');
document.write('margin-right:0%;');
document.write('}');
document.write('</style>');
